<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>247d4634-4500-432d-833a-9275f32989ba</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChatFrontend\ChatFrontend.csproj" />
    <ProjectReference Include="..\WebUI\WebUI.csproj" />
    <ProjectReference Include="..\DEMOMAF.DnDPortal\DEMOMAF.DnDPortal.csproj" />
  </ItemGroup>

</Project>
