<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Components\Pages\ChatInput.razor.js" />
    <None Remove="Components\Pages\ChatMessageList.razor.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.AI.AGUI" Version="1.0.0-preview.251219.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DEMOMAF.ServiceDefaults\DEMOMAF.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Components\Pages\Chat\ChatMessageList.razor.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="Components\Pages\Chat\ChatInput.razor.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>


</Project>
